### ISSUE TITLE
Alcaeus doesn't pass base URI to the JSON-LD deserializer, causes failure to parse contexts using relative IRIs

### ISSUE THREAD

**Issue by alexkreidler** [wikibus/Alcaeus#193]
For resolving relative IRIs in JSON-LD, the document either needs an explicit `@base`, but barring that, it needs the environment that requested the document to properly pass through where the document was received from. 

I have a document that I am trying to load using `Hydra.loadResource("http://localhost:9090/home")`

```json
{
        "@context": "/context",
        "id": "/home",
        "title": "Example People API Server",
        "description": "Using the people Hydra ontology",
        "people": {
            "@id": "/people"
        }
    },
```
For it to be able to resolve the relative `/context` IRI, it needs to know the location of the received document. As alcaeus works right now, I get an error described in https://github.com/rdfjs-base/parser-jsonld/issues/10.

That issue shows the line where `@rdfjs/parser-jsonld` passes on the argument to the `jsonld` argument. However, where we call the appropriate RDF parser here, using `SinkMap`:

https://github.com/wikibus/Alcaeus/blob/c1d6b2fc43ed9934ef5e88b877cbe0be6ef66cca/src/ResponseWrapper.ts#L72

there's a third optional argument to pass through options, in this case `baseURI`. 

AFAIK, JSON-LD is the only RDF serialization to use relative IRIs, so we could pass it through only on the appropriate media type. Or we could pass it through always and hope the other libraries ignore it.

Another choice is whether to pass through `requestedUri`, or `effectiveUri`. The following part of the spec:

> A remote context may also be referenced using a relative URL, which is resolved relative to the location of the document containing the reference. For example, if a document were located at http://example.org/document.jsonld and contained a relative reference to context.jsonld, the referenced context document would be found relative at http://example.org/context.jsonld.

makes me think effectiveUri is the way to go.

**Comment by tpluscode** [comment]
Hey. Thank you for reporting this. Coincidentally I found this omission myself just today while working on some perf improvements (I would like to roll out a `1.0-RC` this week, hopefully tomorrow). The base IRI definitely has to be addressed.

I think your diagnosis is correct. While not an RDF/JS standard, a `baseIRI` parameter is already used by some `@rdfjs/parser-X` packages. Turtle/N3 also support relative URIs after all. 

I would also go for `effectiveUri` which takes redirects into account as described in [RFC3986](https://tools.ietf.org/html/rfc3986#section-5.1.3)
