### ISSUE TITLE
content-type with charset not working

### ISSUE THREAD

**Issue by bergos** [wikibus/Alcaeus#20]
If the `content-type` contains a charset like `application/ld+json; charset=utf-8`, the parser is not found. I think in [this line](https://github.com/wikibus/Alcaeus/blob/master/src/FetchUtil.ts#L82) the charset should be cropped. In `rdf-fetch` it's done like [this](https://github.com/rdf-ext/rdf-fetch-lite/blob/master/lib/patch-response.js#L13).

Example to reproduce the error:
```
const Hydra = require('alcaeus').Hydra

Hydra.loadResource('http://ld.stadt-zuerich.ch/api').then(res => {
  console.log(res)
}).catch((err) => {
  console.error(err)
})
```

**Comment by tpluscode** [comment]
Hi. Thanks for spotting this.

A robust solution would be to actually parse the header. There can be profiles and other unexpected stuff. Do you know any content-type header parser for JS?

**Comment by tpluscode** [comment]
Or maybe it is enough to just truncate everything after the first semicolon 🤔

**Comment by bergos** [comment]
For finding the parser truncating everything after the first semicolon should be ok. Charset should be handled by the stream (hope so...), other stuff is maybe not implemented (yet). Also thought it looks a little bit ugly in `rdf-fetch`, but for all use cases I'm aware of, it should work.

**Comment by tpluscode** [comment]
Published as 0.3.0-a5

**Comment by bergos** [comment]
@tpluscode The [dist](https://unpkg.com/alcaeus@0.3.0-a5/dist/alcaeus.js) in the latest version doesn't contain the fix. Looks like the dist wasn't built. Also unpkg shows an older date for the dist files.

**Comment by tpluscode** [comment]
Bugger. guess I should automate that :)

**Comment by tpluscode** [comment]
Okay, 0.3.0-a6 is correct.

Turns out I had an old npm, which did not do `prepublishOnly` 🤐
