### ISSUE TITLE
Add option to disable all caching to avoid CORS issues

### ISSUE THREAD

**Issue by alexkreidler** [wikibus/Alcaeus#203]
I'm getting
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.w3.org/ns/hydra/core#title.
(Reason: header ‘if-modified-since’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response).
```
It would be nice to disable any caching-related headers so I could avoid this issue. I tried passing `{"if-modified-since": undefined}` as the second argument to `Hydra.loadResource`, but no luck, this actually led to the issue occurring on more URLs.

**Comment by tpluscode** [comment]
Actually, you can do that already by hooking to the `Hydra.cacheStrategy.requestCacheHeaders` function

It has a default value so you might decorate or replace completely:

```typescript
import { Hydra, HydraResponse } from 'alcaeus/web'

const defaultCacheHeaders = Hydra.cacheStrategy.requestCacheHeaders
Hydra.cacheStrategy.requestCacheHeaders = (previous: HydraResponse) => {
  if (previous.response.effectiveUri.startsWith('https://www.w3.org/ns/hydra/core#')) {
    return null
  }
}
```

**Comment by tpluscode** [comment]
But I would repeat what I wrote on [public-linked-json](https://lists.w3.org/Archives/Public/public-linked-json/2020Oct/0003.html)

You could be better off bundling shared vocabularies inside your application using [@zazuko/rdf-vocabularies](https://npm.im/@zazuko/rdf-vocabularies)

Watch out for PR https://github.com/zazuko/rdf-vocabularies/pull/74 which will allow importing the packaged vocabularies statically, synchronously and without requiring a parser

**Comment by alexkreidler** [comment]
Ah, my memory of the capability to configure that was mistaken. Thanks for your response.
