### ISSUE TITLE
Handle operations not connected to the resource IRI

### ISSUE THREAD

**Issue by bergos** [wikibus/Alcaeus#21]
We defined an [API](http://stat.stadt-zuerich.ch/api) which also contains the links to the objects. It was designed like this to reduce the number of requests required to use the API. It looks like Alcaeus can only handle objects which are connected to triples with a subject matching the resource IRI. It would be great to have an option to also access the objects not connected to the resource IRI.

Two ideas how it could be implemented:
- `loadResource` returns also array objects to manually search for the wanted object
- A function which returns an array of objects by type ([DataSet](http://purl.org/linked-data/cube#DataSet) in our example)

Most of the operations in our API return a lot of triples. [This](http://stat.stadt-zuerich.ch/api/dataset/GEB-RAUM-ZEIT/slice) is a good candidate for testing.

**Comment by tpluscode** [comment]
> It would be great to have an option to also access the objects not connected to the resource IRI.

This shouldn't be too hard as Alcaeus already process all resources in the representation and it mean merely changing the returned object. In fact it would also allow arbitrary access to all resources within the representation which are not the requested URI.

> Two ideas how it could be implemented:

From what you propose I assume I'd start building something slightly more sophisticated. `loadResource` could, as you say, return a key-value dictionary of all resources but also expose additional APIs. Based on what you ask here's what I have in mind in TS-like pseudo

``` ts
interface IHydraClient {
  load(uri:string): Promise<IResourceCollection>
}

interface IResourceCollection {
  /**
   * Indexer to look up any arbitrary resource by its id
   */
  [id: string]: IHydraResource;

  /**
   * "A function which returns an array of objects by type"
   */
  ofType(classId: string): Array<IHydraResource>;

   /**
    * A shorthand to the "root" of requested representation
    * Would be usually equivalent to `client.load("xyz")["xyz"]`
    */
   root: IHydraResource; 
}
```

The `root` getter is slightly tricky. In general I want to keep a simple API which replace current usage. I write **usually** because so far I've come to realise that in some cases the neither the root object in JSON-LD terms nor the requested resource is really what the client may really want.

The case I faced was paged collection returned when the client requests the collection itself (eg. `/issues`). In such case the actual root is the page (eg. `/issues?page=1`). Anyway, I digress but maybe this is something that you already notice in your resources?

**Comment by tpluscode** [comment]
@bergos I realise now that there are two possible ways to approach the collection of resources.

For example in your sample there are many resources at the "top" level. That is, resources which are not object of any triple. The entire graph does actually consist of many more resources, which are children of those roots. For example

```json
{
  "@id": "http://ld.stadt-zuerich.ch/statistics/observation/GEB/R00014/ZXXXX2016",
  "@type": "http://purl.org/linked-data/cube#Observation",
  "http://ld.stadt-zuerich.ch/statistics/measure/GEB": {
	"@type": "http://www.w3.org/2001/XMLSchema#double",
	"@value": "7.0E0"
  },
  "http://ld.stadt-zuerich.ch/statistics/property/RAUM": {
	"@id": "http://ld.stadt-zuerich.ch/statistics/code/R00014"
  },
  "http://ld.stadt-zuerich.ch/statistics/property/ZEIT": {
	"@type": "http://www.w3.org/2001/XMLSchema#gYear",
	"@value": "2016"
  },
  "http://purl.org/linked-data/cube#dataSet": {
	"@id": "http://ld.stadt-zuerich.ch/statistics/dataset/GEB-RAUM-ZEIT"
  },
  "http://www.w3.org/2004/02/skos/core#notation": "ZXXXX2016R00014GEBXXX0000XXX0000XXX0000XXX0000XXX0000"
}	
```

My question is what should be the outcome of the code below?

```
const representation = client.loadResource('/api/dataset/GEB-RAUM-ZEIT/slice');
const resource = representation['http://ld.stadt-zuerich.ch/statistics/code/R00014'];
```

Currently it will return any identified resource from the response graph. I am however leaning towards changing this behaviour so that only the topmost resources would be available on the indexer. 

What do you think?

**Comment by bergos** [comment]
I'm not sure if I got you right. From the triple perspective there are multiple `http://ld.stadt-zuerich.ch/statistics/code/R00014` objects, but there can be only one subject with that IRI. In JSON-LD this can be confusing, because it requires to search for the resource with content. This caused already some headaches in our team when we tried to make a JSON API using framing and wanted multiple label properties for the `http://ld.stadt-zuerich.ch/statistics/code/...` IRIs which didn't and should not work in JSON. It could work in JS if the same objects are used, so they don't get out of sync.

`ofType()` should return an array. How many times a type is used depends on the data and is out of scope for Hydra.

**Comment by bergos** [comment]
Finding the right root is also a problem I had in SimpleRDF. The result is the [simplerdf-iri-finder](https://github.com/simplerdf/simplerdf-iri-finder) plugin, which provides rules for `current` (same as requested resource), `byType` (would be `returns` from the Hydra API) or  `bySubjectCount` (triple count one level). They can be combined and custom functions can be also used. Each functions filters the options for the next function. So `current, byType, bySubjectCount` would use the resource, type search will be used if there is no triple and for multiple IRIs for the type the count would be used.

**Comment by tpluscode** [comment]
Hey. Indeed it seems we're talking about two different subjects.

To rephrase my questions: Should the indexer and `ofType` method return resources no matter where in the graph they appear?

To give a more complete example. With the graph below

```json
{
  "@id: "/tomasz",
  "@type": "Person",
  "friend": [{
    "@id": "/Adrian",
    "@type": "Person"
  }, {
    "@id": "/Thomas",
    "@type": "Person"
  }]
}
```

1. Should calling `resources['/Adrian']` return an object or `null`?
1. Should calling `resources.ofType('Person')` return just `/tomasz` or all three resources?

**Comment by tpluscode** [comment]
> it requires to search for the resource with content

I know your pain. Non of the JSON-LD functions are powerful enough.  In Alcaeus the model is thus not plain JSON. I do a similar process to the incomplete `objectify` function proposed in JSON-LD API. Whatever you get from `loadResource` is a fully traversable graph of objects.

**Comment by bergos** [comment]
1. I think it should always return an object
2. It should return all three resources

How would the tree look like if `/Adrian` would have a `friend` property which points to `/tomasz` and no IRI matches the requested resource? One option would be a (complex) logic how to build the tree for all possible options or all resources are accessible which should work for all use cases.

**Comment by tpluscode** [comment]
In the end I arrived at a similar conclusion. The "interesting" resource does not necessarily be the root of whatever graph that the JSON represents. Hence I will return the object always.

**Comment by tpluscode** [comment]
> How would the tree look like if `/Adrian` would have a `friend` property which points to `/tomasz` and no IRI matches the requested resource? 

You mean something like below? (skipping the `@type`)

```json
{
  "@id": "/Adrian",
  "friend": {
    "@id": "/tomasz"
  }
}
```

> One option would be a (complex) logic how to build the tree for all possible options or all resources are accessible which should work for all use cases.

If I understand you correctly, then this will not be necessary. As the consumer of Alcaeus you get a completely traversable graph of JS objects. The return value of `loadResource` is pretty much a key value pair of all resources. Not really a JSON-LD at all:

```json
{
  "/tomasz": {
    "@id": "/tomasz",
    "@type": "Person",
    "friend": [{
      "@id": "/Adrian"
    }, {
      "@id": "/Thomas"
    }]
  },
  "/Adrian": {
    "@type": "Person"
  },
  "/Thomas": {
    "@type": "Person",
    "friend": [{ 
      "@id": "/tomasz"
    }]
  }
}
```

It is pretty much what you get from JSON-LD flatten but then entire tree is processed to make real references. 

Notice I added an additional `</Thomas> friend </Adrian>` triple. With that you could write code not unlike the following

```js
const resource = client.loadResource('/tomasz');
const tomasz = resource['/tomasz'];
// tomasz.friends[1] == "/Thomas"
const adrian = tomasz.friends[1].friends[0];
```
