### ISSUE TITLE
Performance improvements - make Alcaeus lazy

### ISSUE THREAD

**Issue by tpluscode** [wikibus/Alcaeus#24]
Currently Alcaeus is very eager to load and process everything it gets.

It works fine for small datasets but apparently the API exposed by @bergos has a large API doc with 4400+ resources. To process that takes over 40 seconds.

The bottleneck turns out to be a little needed function which finds reverse links between resources such as are not easily visible in a free structure. There are two ways to improve that:

* [x] Make it lazy and only called from resource objects when needed. This alone shaves off 90% of the time
* [ ] Instead of processing JS objects use RDF Ext to run a simple query on the graph
* [ ] Load API Documentation only the first time it is being requested

**Comment by tpluscode** [comment]
Another improvement is to only prosecc subgraphs once any arbitrary resource is retrieved from the graph

**Comment by pavelcerveny** [comment]
Hi,
I have a question. Well I just want to make sure, I'm on the right track. 

How much is the performance issue connected with the parsing and processing incoming data? I mean with the use of dependencies such as: "_jsonld_", "_rdf-ext_", "_rdf-parser-jsonld_", "_rdf-serializer-jsonld-ext_". Of course, I understand that, if that's the case, then there is nothing you can do about it. But I would like to know what's the next big bottleneck of this solution, except the issues you mentioned above.

Thank you

**Comment by pavelcerveny** [comment]
Hi @tpluscode, thank you for your answer, it surely helped.

**Comment by tpluscode** [comment]
This is not obsolete given the changes in the 1.0 branch
