### ISSUE TITLE
Adding @types 

### ISSUE THREAD

**Issue by pavelcerveny** [wikibus/Alcaeus#31]
Hi, could you add types into the package itself or create them in @types/alcaeus ? Thanks

**Comment by tpluscode** [comment]
Hi @pavelcerveny. Please try 0.4.1

**Comment by pavelcerveny** [comment]
Hi, thanks for quick response. Unfortunately, in your code there're hardcoded some paths, please see this error:

> node_modules/alcaeus/dist/src/Resources/HydraResource.d.ts(14,25): error TS2307: Cannot find 
module '../../../../../../../../Users/tomaszpluskiewicz/projects/github/wikibus/heracles/src/TypeCollection'.

**Comment by tpluscode** [comment]
Weird, how did that happen. I regenerated the typing using tsc switch. Any ideas what could have gone wrong?

**Comment by tpluscode** [comment]
Ah apparently it was caused by Microsoft/TypeScript#25511 in typescript ~2.9. Please try again with 0.4.2

**Comment by pavelcerveny** [comment]
Yes, it's working now. Good job in finding the problem.

**Comment by tpluscode** [comment]
Fantastic. You're welcome
