### ISSUE TITLE
Unable to import library in Node environment

### ISSUE THREAD

**Issue by ejbyne** [wikibus/Alcaeus#38]
**Expected Behaviour**
The following code (based on the project documentation) should not throw an error when run in a Node environment:

File `src/index.js`:
```
const { Hydra } = require('alcaeus')
console.log('testing')
```

**Actual Behaviour**
The command `node src/index.js` results in the following syntax error:
```
/Users/ejbyne/projects/json-ld/hydra-client-test/src/alcaeus.js:1
(function (exports, require, module, __filename, __dirname) { import { Hydra } from 'alcaeus'
                                                                     ^
SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
```

**Workaround**
The `main` entrypoint for the Alcaeus module is configured in `package.json` as `lib/index.js`. This code includes ES modules, which are not yet fully supported by Node. I would not expect to need to use Babel to compile my project's dependencies to ES5 (and also came across some problems when I tried to this).

The module is however already compiled to ES5 in the package's `dist` folder. I was able to get my code running by changing the import as follows:

```
const { Hydra } = require('alcaeus/dist/alcaeus')
console.log('testing')
```

**Requested Fix**
Either the above workaround should be made clear in the documentation or, preferably, the entrypoint for the module should point to Node-compatible code. It should not be necessary for the published code to include ES5, ES6 and TypeScript versions of the source code - ES5 alone should suffice.

** Context **
▶ npm -v
6.4.1
▶ node -v
v10.12.0
OS: Linux, MacOS

**Comment by tpluscode** [comment]
Thank you for pointing out this problem @ejbyne 

I think that publishing only ES5 is not really useful for usage with bundlers, which take advantage of static analysis when resolving modules.

Instead I employed a dula-packaging method as described in [In Defense of .js](https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md). 

Please check release `0.4.3-a1` which worked fine for both in node (8+) and webpack.

**Comment by tpluscode** [comment]
By the way, do you find the single-file bundle from `dist` any useful to anyone? I would consider removing it from the build.
