### ISSUE TITLE
Convenience method for dereferencing?

### ISSUE THREAD

**Issue by tpluscode** [wikibus/Alcaeus#55]
Currently, to fetch resources, the client has to be used directly every time

```js
const rep = await client.loadResource('http://www.markus-lanthaler.com/hydra/api-demo/issues/');
const issue = (await client.loadResource(rep.root.members[0].id)).root
```

It could be useful to have a simple method on each object which would follow the self-link (`@id`) and return the representation.

```js
const rep = await client.loadResource('http://www.markus-lanthaler.com/hydra/api-demo/issues/');
const issue = await rep.root.members[0].load()
```

**Comment by tpluscode** [comment]
@alien-mcl, does Heracles have this?

**Comment by alien-mcl** [comment]
Only in very limited degree. Instances of IApiDocumentation interface has getEntryPoint() implementation that calls the client provided to hypermedia processing facility with the entry point URL discovered.
I was thinking about similar approach, but somehow I did hesitate to do so. Currently hypermedia are pure data structures without any logic, which is held by the client and it's dependencies. I somehow like it that way.

But adding such a method would be an easy thing to implement with Heracles.ts as it is now.

**Comment by tpluscode** [comment]
> I somehow like it that way.

> But adding such a method would be an easy thing to implement with Heracles.ts as it is now.

Not asking that. Maybe if you say you like it the way it is, that could be a distinguishing factor between the two clients
