### ISSUE TITLE
Relative Links to ApiDocumentation

### ISSUE THREAD

**Issue by angelo-v** [wikibus/Alcaeus#56]
## Expected behaviour

**Given** The client at `https://client.example` loads an API entrypoint at `http://api.example/`
**And** The Link-Header of the response contains a relative link to the API doc: `Link: </doc>; rel="http://www.w3.org/ns/hydra/core#apiDocumentation"`
**When** the client loads the API doc
**Then** it uses the absolute URI `http://api.example/doc`

## Actuall behaviour

**Then** it uses the absolute URI `http://client.example/doc`

## Additional information

https://tools.ietf.org/html/rfc3986#section-5.1.3

> 5.1.3.  Base URI from the Retrieval URI

   > If no base URI is embedded and the representation is not encapsulated
   within some other entity, then, if a URI was used to retrieve the
   representation, that URI shall be considered the base URI.  Note that
   if the retrieval was the result of a redirected request, the last URI
   used (i.e., the URI that resulted in the actual retrieval of the
   representation) is the base URI.

**Comment by tpluscode** [comment]
Hey, thanks for reporting this Angelo. I shall prioritise this.

**Comment by tpluscode** [comment]
https://generic.hypermedia.app/#/https://hydra-movies.herokuapp.com/

:tada:
