### ISSUE TITLE
HydraResource.operations blows up when ApiDocumentation is missing

### ISSUE THREAD

**Issue by jerben** [wikibus/Alcaeus#57]
### Actual behaviour
When there is no ApiDocumentation and I access the property `operations` on a `HydrarResource`, alcaeus fails with: `TypeError: Cannot read property 'getOperations' of undefined`.

### Expected behaviour
When there is no ApiDocumentation and I access the property `operations` on a `HydrarResource`, alcaeus either 
* returns null and logs a warning 
* throws a named error with an appropriate message.

### Notes
As a newcomer this shows that an API has to implement ApiDocumentation in order to conform to Hydra.

**Comment by tpluscode** [comment]
@jerben what do you think about `Maybe` monad? I wrapped the value from `apiDocumentation` to avoid null checks everywhere it's used.

Any code accessing `apiDocumentation` will have to change to 

```js
apiDocumentation.map(value => /* ... */)
```

where the callback gets called only if the api documentation really exists.

I realise this is breaking change but I think it's worth it.

**Comment by jerben** [comment]
@tpluscode I like the use of `Maybe` and I agree that the breaking change is worth it.

I am in fact using https://github.com/cbowdon/TsMonad#general-maybe-usage in the code that uses Alcaeus. You might not want to pull it in as dependency but maybe it makes sense to adjust the `Maybe` implementation so that the type matches with that one?

**Comment by tpluscode** [comment]
Hm, it's just 1.3 kB gzipped. I don't really mind pulling it in as dependency.
